name: Update rs-distances Submodule

on: 
  push:
    branches: [ main ]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Setup Git User
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "<your-email>"

    - name: Update rs-distances Submodule
      run: |
        cd rs-distances
        git checkout master
        git pull origin master
        cd ..
        git diff --cached --exit-code || git commit -am "Updated rs-distances submodule"

    - name: Push Changes
      run: |
        git push